
spring:
  profiles:
    active: #spring.profiles.active#
  aop:
    proxy-target-class: true
  datasource:
    url: jdbc:mysql://localhost:3306/sc_process?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: hhh123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  activiti:
    # 自动部署验证设置:true-开启（默认）、false-关闭
    check-process-definitions: false
server:
  port: 80
    #自动部署文件路径后缀
#   process-definition-location-prefix: classpath:/processes/
#   process-definition-location-suffixes:
#      - **.bpmn
#      - **.bpmn20.xml